dataset <- read.table("household_power_consumption.txt", header=TRUE, sep=";", colClasses=c("character","character",rep("numeric",7)),na.strings="?" )
dim(dataset)
attach(dataset)
dataset$Date <- as.Date(dataset$Date, format="%d/%m/%Y")
dataSubset <- subset(dataset, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
dateTime <- paste(as.Date(dataSubset$Date), dataSubset$Time)
dataSubset$dateTime <- as.POSIXct(dateTime)
dim(dataSubset)
attach(dataSubset)
png(filename="plot1.png", width=480, height=480, units="px", bg="transparent")
hist(dataSubset$Global_active_power, col="Red", main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", breaks=12, ylim=c(0,1200))
dev.off()