dataset <- read.table("household_power_consumption.txt", header=TRUE, sep=";", colClasses=c("character","character",rep("numeric",7)),na.strings="?" )
dim(dataset)
attach(dataset)
dataset$Date <- as.Date(dataset$Date, format="%d/%m/%Y")
dataSubset <- subset(dataset, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
dateTime <- paste(as.Date(dataSubset$Date), dataSubset$Time)
dataSubset$dateTime <- as.POSIXct(dateTime)
dim(dataSubset)
attach(dataSubset)
png(filename="plot2.png", width=480, height=480, units="px", bg="transparent")
plot(dataSubset$dateTime, dataSubset$Sub_metering_1, type = "l",col = "black", xlab = "", ylab = "Energy sub metering")
lines(dataSubset$dateTime, dataSubset$Sub_metering_2, col = "red")
lines(dataSubset$dateTime, dataSubset$Sub_metering_3, col = "blue")
legend("topright", col = c("black", "red", "blue"),c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lwd = 1)
dev.off()